############
# zshrc 
############
# Path to your oh-my-zsh installation.
export ZSH="/Users/andrewwray/.oh-my-zsh"

# antigen setup (Plugins)
source ~/.config/antigen.zsh
antigen init ~/.config/antigenrc

# aliases
alias reloadzsh="source ~/.config/zshrc && clear && ls"
alias vim="nvim"
alias zshconf="vim ~/.config/zshrc"
alias vimconf="vim -S ~/.vim/vimconf.vim"
alias nvimconf="vim ~/.config/nvim/init.vim"
alias tmuxconf="vim ~/.tmux.conf"

# yadm
alias yst="yadm status"
alias yc="yadm commit"
alias ya="yadm add"
alias yau="yadm add -u"
alias yp="yadm push"

# tmux
alias tma="tmux attach -t"
alias tls="tmux ls"
alias tn="tmux new -s"

# jupyter 
alias jl="conda activate julab && jupyter lab"

# aws 
alias awsconf="vim ~/.aws/" 
alias awsprof="~/Documents/setup/which_aws.sh"

# startup script (starts tmux and a jupyter lab kernel)
alias jlstart="~/Documents/setup/startup.sh"

# plugins 
plugins=(git aws brew vi-mode)

# pythonpath
export PYTHONPATH='/Users/andrewwray/Documents/DataScience/experimental/util/trunk/:/Users/andrewwray/Documents/DataScience/pipelines/trunk'

source $ZSH/oh-my-zsh.sh

# >>> conda initialize >>>
# !! Contents within this block are managed by 'conda init' !!
__conda_setup="$('/usr/local/Caskroom/miniconda/base/bin/conda' 'shell.zsh' 'hook' 2> /dev/null)"
if [ $? -eq 0 ]; then
    eval "$__conda_setup"
else
    if [ -f "/usr/local/Caskroom/miniconda/base/etc/profile.d/conda.sh" ]; then
        . "/usr/local/Caskroom/miniconda/base/etc/profile.d/conda.sh"
    else
        export PATH="/usr/local/Caskroom/miniconda/base/bin:$PATH"
    fi
fi
unset __conda_setup
# <<< conda initialize <<<

