############
# zshrc 
############
# Path to your oh-my-zsh installation.
export ZSH="/Users/andrewwray/.config/oh-my-zsh"

# antigen setup (Plugins)
source ~/.config/antigen.zsh

antigen use oh-my-zsh
antigen bundle git
antigen bundle tmux
antigen bundle svn
antigen bundle aws
antigen bundle brew
antigen bundle pip
antigen bundle command-not-found
antigen bundle copydir
antigen bundle copyfile
antigen bundle fzf
antigen bundle themes
antigen bundle esc/conda-zsh-completion
antigen bundle desyncr/auto-ls
antigen bundle Tarrasch/zsh-functional

antigen bundle zsh-users/zsh-syntax-highlighting

#antigen theme alanpeabody
#antigen theme jackharrisonsherlock/common
antigen theme af-magic

antigen apply

# aliases
alias reloadzsh="source ~/.config/zshrc"
alias vim="nvim"
alias zshconf="vim ~/.config/zshrc"
alias vimconf="vim ~/.vim/vimrc"
alias nvimconf="vim ~/.config/nvim/init.vim"
alias tmuxconf="vim ~/.tmux.conf"

# yadm
alias yst="yadm status"
alias yc="yadm commit"
alias ya="yadm add"
alias yau="yadm add -u"


# jupyter 
alias jl="conda activate julab && jupyter lab"

# aws 
alias awsconf="vim ~/.aws/" 
alias awsprof="~/Documents/setup/which_aws.sh"

# plugins 
plugins=(git aws brew vi-mode)


# pythonpath
export PYTHONPATH='/Users/andrewwray/Documents/DataScience/experimental/util/trunk/:/Users/andrewwray/Documents/DataScience/pipelines/trunk'


#/Users/andrewwray/Documents/setup/aws_on_startup.sh

source $ZSH/oh-my-zsh.sh


ls 




























































































# Uncomment the following line to use case-sensitive completion.
# CASE_SENSITIVE="true"

# Uncomment the following line to use hyphen-insensitive completion.
# Case-sensitive completion must be off. _ and - will be interchangeable.
# HYPHEN_INSENSITIVE="true"

# Uncomment the following line to disable bi-weekly auto-update checks.
# DISABLE_AUTO_UPDATE="true"

# Uncomment the following line to automatically update without prompting.
# DISABLE_UPDATE_PROMPT="true"

# Uncomment the following line to change how often to auto-update (in days).
# export UPDATE_ZSH_DAYS=13

# Uncomment the following line if pasting URLs and other text is messed up.
# DISABLE_MAGIC_FUNCTIONS="true"

# Uncomment the following line to disable colors in ls.
# DISABLE_LS_COLORS="true"

# Uncomment the following line to disable auto-setting terminal title.
# DISABLE_AUTO_TITLE="true"

# Uncomment the following line to enable command auto-correction.
# ENABLE_CORRECTION="true"

# Uncomment the following line to display red dots whilst waiting for completion.
# Caution: this setting can cause issues with multiline prompts (zsh 5.7.1 and newer seem to work)
# See https://github.com/ohmyzsh/ohmyzsh/issues/5765
# COMPLETION_WAITING_DOTS="true"

# Uncomment the following line if you want to disable marking untracked files
# under VCS as dirty. This makes repository status check for large repositories
# much, much faster.
# DISABLE_UNTRACKED_FILES_DIRTY="true"

# Uncomment the following line if you want to change the command execution time
# stamp shown in the history command output.
# You can set one of the optional three formats:
# "mm/dd/yyyy"|"dd.mm.yyyy"|"yyyy-mm-dd"
# or set a custom format using the strftime function format specifications,
# see 'man strftime' for details.
# HIST_STAMPS="mm/dd/yyyy"

# Would you like to use another custom folder than $ZSH/custom?
# ZSH_CUSTOM=/path/to/new-custom-folder


# Which plugins would you like to load?
# Standard plugins can be found in $ZSH/plugins/
# Custom plugins may be added to $ZSH_CUSTOM/plugins/
# Example format: plugins=(rails git textmate ruby lighthouse)
# Add wisely, as too many plugins slow down shell startup.

# User configuration

# export MANPATH="/usr/local/man:$MANPATH"

# You may need to manually set your language environment
# export LANG=en_US.UTF-8

# Preferred editor for local and remote sessions
# if [[ -n $SSH_CONNECTION ]]; then
#   export EDITOR='vim'
# else
#   export EDITOR='mvim'
# fi

# Compilation flags
# export ARCHFLAGS="-arch x86_64"

# Set personal aliases, overriding those provided by oh-my-zsh libs,
# plugins, and themes. Aliases can be placed here, though oh-my-zsh
# users are encouraged to define aliases within the ZSH_CUSTOM folder.
# For a full list of active aliases, run `alias`.
#
# Example aliases

# >>> conda initialize >>>
# !! Contents within this block are managed by 'conda init' !!
__conda_setup="$('/usr/local/Caskroom/miniconda/base/bin/conda' 'shell.zsh' 'hook' 2> /dev/null)"
if [ $? -eq 0 ]; then
    eval "$__conda_setup"
else
    if [ -f "/usr/local/Caskroom/miniconda/base/etc/profile.d/conda.sh" ]; then
        . "/usr/local/Caskroom/miniconda/base/etc/profile.d/conda.sh"
    else
        export PATH="/usr/local/Caskroom/miniconda/base/bin:$PATH"
    fi
fi
unset __conda_setup
# <<< conda initialize <<<

