############
# zshrc 
############
# Path to your oh-my-zsh installation.
export ZSH="/Users/andrewwray/.config/oh-my-zsh"
source $ZSH/oh-my-zsh.sh

# antigen setup (Plugins)
source ~/.config/antigen.zsh
antigen init ~/.config/antigenrc


# aliases
alias reloadzsh="source ~/.config/zshrc && clear && ls"
#alias vim="nvim"
alias zshconf="vim ~/.config/zshrc"
alias vimconf="vim -S ~/.vim/vimconf.vim"
alias nvimconf="vim ~/.config/nvim/init.vim"
alias tmuxconf="vim ~/.tmux.conf"
alias sshconf="vim ~/.ssh/config"

# yadm
alias yst="yadm status"
alias yc="yadm commit"
alias ya="yadm add"
alias yau="yadm add -u"
alias yp="yadm push"

# tmux
alias tma="tmux attach -t"
alias tls="tmux ls"
alias tn="tmux new -s"

# jupyter 
alias jl="conda activate julab && jupyter lab" 
alias jlstart="/Users/andrewwray/Documents/setup/startup.sh"

# aws 
#alias awsconf="vim ~/.aws/" 
#alias awsprof="~/Documents/setup/which_aws.sh"
#alias start_ec2="~/Documents/setup/start_ec2.sh"


# plugins 
plugins=(git aws vi-mode)

# pythonpath
export PYTHONPATH='~/DataScience/experimental/util/trunk/:~/Documents/DataScience/pipelines/trunk:~/Documents/DataScience/nn/trunk/'
